spring:

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.53.86.200:1521:orcl
    username: hyhis
    password: hyhis
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: JAFY
#    password: JAFY

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 0
#    database: 00
#    password: 123456
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1

server:
  port: 8081

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: info
  path: ./logs
  config: classpath:logback-spring.xml


#  application:
#    name: data-multidatasource
    #  second-datasource:
    #    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    #    url: jdbc:hsqldb:hsql://localhost:9001/sampledata
    #    username: pentaho_user
    #    password: cGFzc3dvcmQ=
    #mybatis:
  ##  config-location: classpath:mybatis-config.xml
  ##  mapper-locations: classpath:mapper/*.xml